[IT-2594] Create template for setting a DNS CNAME
Sage-Bionetworks/aws-infra pull request #372
Opened 2023-02-01 22:43 UTC by jesusaurus

Create a template inspired by the s3-redirector template, but intended to redirect to a Cloudfront distribution created in another stack.

This is needed to create a friendly DNS name for the lambda-mips-api Cloudfront distribution.

2023-02-02 20:01 UTC, zaro0508 requested changes
i think the [s3-redirector.yaml](https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/s3-redirector.yaml) template is already doing the same thing?  

it's used here https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/org-formation/800-redirects/_tasks.yaml#L6

2023-02-02 21:10 UTC, xschildw reviewed
I would remove references to 'redirect', there's no redirection (in the HTTP 30x sense) it's just different names that point to the same IP addresses. If we do a redirect, we'll end up on the target with its raw/internal name (maybe it does not matter since it's not meant to be seen in a browser).

2023-02-03 18:23 UTC, jesusaurus commented
@zaro0508 the s3-redirector template is doing too much for our lambda CNAME use-case, this template is only creating the CNAME. And it might be nice to refactor s3-redirector to leverage this template instead of creating a duplicate resource definition, but I think that should be a follow-up effort.

2023-02-03 23:16 UTC, zaro0508 approved these changes
@xschildw comment is interesting however i don't really understand what it means.  LGTM.

2023-02-07 21:56 UTC, merged