IT-2736: Setup templates
Sage-Bionetworks/aws-infra pull request #394
Opened 2023-06-20 19:41 UTC by xschildw

This PR installs the templates needed to move from the existing github-oidc-provider.j2 to the new .njk template (with support for multiple repos.

2023-06-21 19:37 UTC, zaro0508 requested changes

2023-06-21 19:37 UTC, zaro0508 commented on templates/IAM/oidc-provider.yaml
> +    Type: AWS::IAM::OIDCProvider
why do we need this template at all?  

also, instead of creating this wrapper why would you not just use this CFN resources directly?

2023-06-21 19:37 UTC, zaro0508 commented on templates/IAM/github-oidc-provider-access.njk
> +{# Allow Github to access AWS without giving github AWS credentials               #}
now we have this file and `github-oidc-provider.j2`.  do we need both files?

2023-06-21 19:37 UTC, zaro0508 commented on templates/IAM/github-oidc-provider-access.njk
> +      Description: "The name of the github organization"
GitHubOrg is a jinja parameter, not a CFN parameter.  you can remove this.

2023-06-21 19:37 UTC, zaro0508 commented on templates/IAM/github-oidc-provider-access.njk
> +{% endif %}
are we going to support this compatibility?  or do we only want this for sceptre?  if we want to support this then it needs to be tested and documented

2023-06-22 18:57 UTC, zaro0508 requested changes

2023-06-22 18:57 UTC, zaro0508 commented on templates/IAM/github-oidc-provider-access.njk
> +{#  Parameters:                                                                   #}
we should probably add some comments similar to https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/org-formation/650-identity-providers/github-oidc-provider-access.njk#L1-L11

2023-06-22 18:57 UTC, zaro0508 commented on templates/IAM/github-oidc-provider-access.njk
> +      Description: "The name of the github organization"
GitHubOrg parameter has not been removed?

2023-06-22 19:53 UTC, xschildw commented on templates/IAM/github-oidc-provider.j2
> -  ThumbprintList:
The provider is created in separate stack, so not needed anymore.

2023-06-23 20:12 UTC, zaro0508 requested changes

2023-06-23 20:12 UTC, zaro0508 commented on templates/IAM/github-oidc-provider.j2
> +    {% set GitHubOrg = sceptre_user_data.GitHubOrg %}
you'll need to put this in a separate if condition..

```
{% if sceptre_user_data.GitHubOrg is defined %}
    {% set GitHubOrg = sceptre_user_data.GitHubOrg %}
{% endif %}
```

2023-06-23 21:12 UTC, zaro0508 approved these changes

2023-06-23 21:18 UTC, merged