IT-3162: A template to create a certificate with alt names
Sage-Bionetworks/aws-infra pull request #397
Opened 2023-09-19 18:01 UTC by xschildw

This PR creates a template to create a certificate with alternate subject names.
The existing template supports creating certs that cover *.<domainName> or xxx.domainName. 
Should I update existing instead?

2023-09-19 18:41 UTC, xschildw commented
The changes to S3WebCouldfront lock down the bucket to be accessed only through Cloudfront and other misc changes from recent versions.

2023-09-21 16:20 UTC, xschildw commented
Deployed both manually to create a test bucket and check the GH workflow.

2023-09-21 16:49 UTC, zaro0508 requested changes
it's hard to tell how this is going to be used.  would you be able to craft a PR that shows the usage for these changes?

2023-09-21 16:49 UTC, zaro0508 commented on templates/acm-certificate-alt-names.yaml
> +# Setting up a certificate requires a manual step to enter the DNS Validation on godaddy.
is there an existing folder we can put this file in?  if not them maybe make a folder?

I don't understand the intention of this file.  is it meant to replace the existing acm-certificates.yaml file?  is it meant to provide additional functionality to acm-certifcates.yaml?  is it meant for a completely different use case than acm-certificates.yaml?

2023-09-21 16:49 UTC, zaro0508 commented on templates/acm-certificate-alt-names.yaml
> +          ValidationDomain: !If [HasValidationDomainName, !Ref ValidationDomainName, !Ref DomainName]
since AlternativeNames and ValidateDomainName are optional would this even work if user decides to not provide values for those parameters?

2023-09-21 16:49 UTC, zaro0508 commented on templates/acm-certificate-alt-names.yaml
> +      Tags:
tags are no longer needed in templates.  we should be deploying with cloudformation tags

2023-09-21 16:49 UTC, zaro0508 commented on templates/managed-s3WebCloudfront.yaml
> +    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
this seems like a drastic change to this template.  what's the purpose?

2023-09-21 16:49 UTC, zaro0508 commented on templates/acm-certificate-alt-names.yaml
> +      SubjectAlternativeNames: !If [HasAlternativeNames, !Split [',', !Ref AlternativeNames], !Ref AWS::NoValue ]
you don't have to use the split if you just changed the AlternativeNames parameter to accept a List instead of a string

2024-09-03 03:04 UTC, closed without merging